// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPuIJKxRSDXd8KsKPag2tpQtDqb9SBdh0',
    appId: '1:342239774164:android:b08da25d01188e004ac241',
    messagingSenderId: '342239774164',
    projectId: 'financepp-4f4bc',
    storageBucket: 'financepp-4f4bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPuIJKxRSDXd8KsKPag2tpQtDqb9SBdh0',
    appId: '1:342239774164:ios:1c8ee5b2e25c8a2b4ac241',
    messagingSenderId: '342239774164',
    projectId: 'financepp-4f4bc',
    storageBucket: 'financepp-4f4bc.appspot.com',
    iosBundleId: 'com.financepp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Ro4eNiUNri0PshwLs0gNvoOl6ZSqXj0',
    appId: '1:342239774164:web:19f66e60b54009924ac241',
    messagingSenderId: '342239774164',
    projectId: 'financepp-4f4bc',
    authDomain: 'financepp-4f4bc.firebaseapp.com',
    storageBucket: 'financepp-4f4bc.appspot.com',
    measurementId: 'G-KKZQ4RBTBZ',
  );
}
